export const categoryOrder: string[] = [
  "Balise Head",
  "SEO",
  "Images",
  "Performance",
  "HTML",
  "Accessibilité",
  "Style",
];

export const checklist = [
  {
    id: 1,
    content: "Balise DOCTYPE & charset sur toutes les pages",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 2,
    content: 'Attribut de "lang" et "ltr" sur la balise "<html>"',
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 3,
    content: "Balise Viewport : correctement déclarée.",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 4,
    content: "Balise meta (title, ...) par pages",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 5,
    content: 'Balise <link rel="canonical"> par pages',
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 6,
    content: "Lien des langues alternatives par pages",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 7,
    content: "Lien de la sitemap.xml ou du flux RSS",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 8,
    content: "Favicons : Chaque favicon s'affiche correctement",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 9,
    content: "OpenGraph : Apple, Windows, twitter & Facebook",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 10,
    content: "Commentaires conditionnels IE si nécessaire",
    status: false,
    category: "Balise Head",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 11,
    content: "Google Analytics : installé et configuré",
    status: false,
    category: "SEO",
    myrdhin: false,
    externalUrl: "https://developers.google.com/analytics?hl=fr",
  },
  {
    id: 12,
    content: "sitemap.xml : existe et soumis à Google",
    status: false,
    category: "SEO",
    myrdhin: false,
    externalUrl: "https://bespin.lintermediaire.be/sitemap",
  },
  {
    id: 13,
    content: "robots.txt : Le fichier robots.txt bien configuré",
    status: false,
    category: "SEO",
    myrdhin: false,
    externalUrl: "https://bespin.lintermediaire.be/seo-tools",
  },
  {
    id: 14,
    content: "Données structurées : Respect de la sémantique",
    status: false,
    category: "SEO",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 15,
    content: 'Jolies URLS & slug sans le "www"',
    status: false,
    category: "SEO",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 16,
    content: "Compression : WebP pour les pages critiques",
    status: false,
    category: "Images",
    myrdhin: false,
    externalUrl: "https://tinypng.com",
  },
  {
    id: 17,
    content: "Texte title & alt : décrivant visuellement l’image",
    status: false,
    category: "Images",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 18,
    content: "Lazy loading : Les images sont chargées en différé",
    status: false,
    category: "Images",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 19,
    content: "Srcset : pour fournir l’image la plus adaptée",
    status: false,
    category: "Images",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 20,
    content: "Largeur et hauteur : Définiir les attributs (css)",
    status: false,
    category: "Images",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 21,
    content: "H1 : Toutes les pages ont un titre différent",
    status: false,
    category: "Accessibilité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 22,
    content: "Sémantique : hierarchie respectée (ex. : H1 à H6)",
    status: false,
    category: "Accessibilité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 23,
    content: "Contraste des couleurs : normes WCAG AA/AAA",
    status: false,
    category: "Accessibilité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 24,
    content: "(aria)-label: associé à chaque élément (form)",
    status: false,
    category: "Accessibilité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 25,
    content: "Focus : Si désactivé, stylé via le CSS",
    status: false,
    category: "Accessibilité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 26,
    content: "Code minifié : Poids des page < 500 Ko",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 27,
    content: "Chargement différé : img, js et CSS en différé",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 28,
    content: "Cookies : < 4 096 octets. et < 20 par site",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 29,
    content: "Google PageSpeed : toutes les pages > de 80/100",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "https://pagespeed.web.dev",
  },
  {
    id: 30,
    content: "Préchargement : scripts préchargé et à la fin",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 31,
    content: "Minification : code minifié et concaténé",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 32,
    content: "Aucun code JS intégré à l'HTML",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 33,
    content: "Balise noscript : dans le corps HTM (React.js)",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 34,
    content: "Non bloquant : via async ou via defer",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 35,
    content: "Modernizr : pour des fonctionnalités spécifiques",
    status: false,
    category: "Performance",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 36,
    content: "Pages erreur 404 présente",
    status: false,
    category: "HTML",
    myrdhin: true,
    externalUrl: "",
  },
  {
    id: 37,
    content: "Noopener : pour les liens externes",
    status: false,
    category: "HTML",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 38,
    content: "Suppression des commentaires",
    status: false,
    category: "HTML",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 39,
    content: "Conformité W3C : chaque pages testées",
    status: false,
    category: "HTML",
    myrdhin: false,
    externalUrl: "https://validator.w3.org/nu",
  },
  {
    id: 40,
    content: "Aucun lien brisé. (log erreur 404)",
    status: false,
    category: "HTML",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 41,
    content: "Font : WOFF, WOFF2 & TTF et < 100 ko",
    status: false,
    category: "Style",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 42,
    content: "Design : tous les écrans (+print), OS et navigateurs",
    status: false,
    category: "Style",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 43,
    content: "CSS : concaténé et en évitant <style> ou en ligne",
    status: false,
    category: "Style",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 44,
    content: "Réinitialisation CSS : normalisation et version",
    status: false,
    category: "Style",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 45,
    content: "Validateur CSS : minifié, testé et corrigé",
    status: false,
    category: "Style",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 46,
    content: "Si CMS MAJ : Thèmes, pluggins et CMS",
    status: false,
    category: "Sécurité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 47,
    content: "Backups",
    status: false,
    category: "Sécurité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 48,
    content: "Activation du Pare-feu",
    status: false,
    category: "Sécurité",
    myrdhin: false,
    externalUrl: "",
  },
  {
    id: 49,
    content: "Si PHP : Configuation .htacess + MAJ de PHP",
    status: false,
    category: "Sécurité",
    myrdhin: false,
    externalUrl: "https://bespin.lintermediaire.be/htaccess",
  },
  {
    id: 50,
    content: "Activation du certificat SSL",
    status: false,
    category: "Sécurité",
    myrdhin: false,
    externalUrl: "",
  },
];
